In [3]:
import pandas

In [4]:
pandas.__version__

'2.3.2'

In [5]:
# !pip install "pandas==2.3.2"

In [6]:
import pandas as pd

In [7]:
dir(pd)
pd.cut

<function pandas.core.reshape.tile.cut(x, bins, right: 'bool' = True, labels=None, retbins: 'bool' = False, precision: 'int' = 3, include_lowest: 'bool' = False, duplicates: 'str' = 'raise', ordered: 'bool' = True)>

In [8]:
help(pd.crosstab)

Help on function crosstab in module pandas.core.reshape.pivot:

crosstab(
    index,
    columns,
    values=None,
    rownames=None,
    colnames=None,
    aggfunc=None,
    margins: 'bool' = False,
    margins_name: 'Hashable' = 'All',
    dropna: 'bool' = True,
    normalize: "bool | Literal[0, 1, 'all', 'index', 'columns']" = False
) -> 'DataFrame'
    Compute a simple cross tabulation of two (or more) factors.

    By default, computes a frequency table of the factors unless an
    array of values and an aggregation function are passed.

    Parameters
    ----------
    index : array-like, Series, or list of arrays/Series
        Values to group by in the rows.
    columns : array-like, Series, or list of arrays/Series
        Values to group by in the columns.
    values : array-like, optional
        Array of values to aggregate according to the factors.
        Requires `aggfunc` be specified.
    rownames : sequence, default None
        If passed, must match number of row arrays passed.
    colnames : sequence, default None
        If passed, must match number of column arrays passed.
    aggfunc : function, optional
        If specified, requires `values` be specified as well.
    margins : bool, default False
        Add row/column margins (subtotals).
    margins_name : str, default 'All'
        Name of the row/column that will contain the totals
        when margins is True.
    dropna : bool, default True
        Do not include columns whose entries are all NaN.
    normalize : bool, {'all', 'index', 'columns'}, or {0,1}, default False
        Normalize by dividing all values by the sum of values.

        - If passed 'all' or `True`, will normalize over all values.
        - If passed 'index' will normalize over each row.
        - If passed 'columns' will normalize over each column.
        - If margins is `True`, will also normalize margin values.

    Returns
    -------
    DataFrame
        Cross tabulation of the data.

    See Also
    --------
    DataFrame.pivot : Reshape data based on column values.
    pivot_table : Create a pivot table as a DataFrame.

    Notes
    -----
    Any Series passed will have their name attributes used unless row or column
    names for the cross-tabulation are specified.

    Any input passed containing Categorical data will have **all** of its
    categories included in the cross-tabulation, even if the actual data does
    not contain any instances of a particular category.

    In the event that there aren't overlapping indexes an empty DataFrame will
    be returned.

    Reference :ref:`the user guide <reshaping.crosstabulations>` for more examples.

    Examples
    --------
    >>> a = np.array(["foo", "foo", "foo", "foo", "bar", "bar",
    ...               "bar", "bar", "foo", "foo", "foo"], dtype=object)
    >>> b = np.array(["one", "one", "one", "two", "one", "one",
    ...               "one", "two", "two", "two", "one"], dtype=object)
    >>> c = np.array(["dull", "dull", "shiny", "dull", "dull", "shiny",
    ...               "shiny", "dull", "shiny", "shiny", "shiny"],
    ...              dtype=object)
    >>> pd.crosstab(a, [b, c], rownames=['a'], colnames=['b', 'c'])
    b   one        two
    c   dull shiny dull shiny
    a
    bar    1     2    1     0
    foo    2     2    1     2

    Here 'c' and 'f' are not represented in the data and will not be
    shown in the output because dropna is True by default. Set
    dropna=False to preserve categories with no data.

    >>> foo = pd.Categorical(['a', 'b'], categories=['a', 'b', 'c'])
    >>> bar = pd.Categorical(['d', 'e'], categories=['d', 'e', 'f'])
    >>> pd.crosstab(foo, bar)
    col_0  d  e
    row_0
    a      1  0
    b      0  1
    >>> pd.crosstab(foo, bar, dropna=False)
    col_0  d  e  f
    row_0
    a      1  0  0
    b      0  1  0
    c      0  0  0

In [9]:
pd.read_csv?

In [10]:
!wget https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

--2025-09-14 09:27:10--  https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/jonfernandes/pandas_essential/main/olympics_1896_2004.csv [following]
--2025-09-14 09:27:11--  https://raw.githubusercontent.com/jonfernandes/pandas_essential/main/olympics_1896_2004.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2398388 (2.3M) [text/plain]
Saving to: ‘olympics_1896_2004.csv.2’

olympics_1896_2004. 100%[===================>]   2.29M  10.0MB/s    in 0.2s

2025-09-14 09:27:11 (10.0 MB/s) - ‘olympics_1896_2004.csv.2’ saved [2398388/2398388]

In [11]:
!curl -O https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

In [12]:
df = pd.read_csv("https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv", skiprows=5)

In [13]:
len(df)

27174

In [14]:
df.shape

(27174, 11)

In [15]:
df.head(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3

In [16]:
df.tail(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [17]:
df.sample(3)

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
8093,1952,Helsinki,Cycling,Cycling Track,"ROBINSON, Raymond Leonard",RSA,Men,2000m tandem,M,Silver,2
18479,1988,Seoul,Wrestling,Wrestling Free.,"HAN, Myung-Woo",KOR,Men,74 - 82kg (middleweight),M,Gold,1
20935,1992,Barcelona,Rowing,Rowing,"RADUCANU, Dumitru",ROU,Men,pair-oared shell with coxswain (2+),M,Bronze,3

In [18]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27174 entries, 0 to 27173
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Year          27174 non-null  int64
 1   City          27174 non-null  object
 2   Sport         27174 non-null  object
 3   Discipline    27174 non-null  object
 4   Athlete Name  27174 non-null  object
 5   NOC           27174 non-null  object
 6   Gender        27174 non-null  object
 7   Event         27174 non-null  object
 8   Event Gender  27174 non-null  object
 9   Medal         27174 non-null  object
 10  Position      27174 non-null  int64
dtypes: int64(2), object(9)
memory usage: 13.7 MB

In [19]:
df.describe(include="all")

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
count,27174.000000,27174,27174,27174,27174,27174,27174,27174,27174,27174,27174.000000
unique,NaN,21,42,55,19991,132,2,572,3,3,NaN
top,NaN,Athens,Aquatics,Athletics,"LATYNINA, Larisa",USA,Men,football,M,Gold,NaN
freq,NaN,2149,3481,3271,18,4020,20611,1279,18995,9181,NaN
mean,1964.685803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.992566
std,31.590396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.817469
min,1896.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25%,1936.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
50%,1972.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000
75%,1992.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000
max,2004.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000

In [20]:
df

,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
...,...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [21]:
pd.get_option("display.max_rows")

60

In [22]:
pd.set_option("display.max_rows", 60)

In [23]:
pd.get_option("display.max_columns")

20

In [24]:
pd.get_option("display.width")

80

In [25]:
df.Discipline

0        Cycling Track
1        Cycling Track
2            Athletics
3            Athletics
4            Athletics
             ...
27169          Fencing
27170          Fencing
27171          Fencing
27172          Fencing
27173          Fencing
Name: Discipline, Length: 27174, dtype: object

In [26]:
df.Discipline.dtype

dtype('O')

In [27]:
type(df.Discipline)

pandas.core.series.Series

In [28]:
df.columns

Index(['Year', 'City', 'Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal', 'Position'],
      dtype='object')

In [29]:
list(df.columns)

['Year',
 'City',
 'Sport',
 'Discipline',
 'Athlete Name',
 'NOC',
 'Gender',
 'Event',
 'Event Gender',
 'Medal',
 'Position']

In [30]:
df.columns.tolist()  # zoptymalizowana do sczytywania indexów

['Year',
 'City',
 'Sport',
 'Discipline',
 'Athlete Name',
 'NOC',
 'Gender',
 'Event',
 'Event Gender',
 'Medal',
 'Position']

In [31]:
df["Year"].unique()

array([1896, 1900, 1904, 1908, 1912, 1920, 1924, 1928, 1932, 1936, 1948,
       1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004])

In [32]:
df["Year"].value_counts(normalize=True) * 100

Year
2000    7.415176
2004    7.352616
1996    6.841098
1992    6.274380
1988    5.689262
1984    5.369103
1980    5.104144
1976    4.802385
1920    4.776625
1972    4.360786
1968    3.794068
1964    3.716788
1952    3.271510
1956    3.256790
1912    3.256790
1924    3.253110
1960    3.245750
1936    3.219990
1948    2.995510
1908    2.958711
1928    2.612792
1932    2.263193
1900    1.884154
1904    1.729594
1896    0.555678
Name: proportion, dtype: float64

In [33]:
df["Year"].max() - df["Year"].min()

np.int64(108)

In [34]:
df["Medal"].unique()

array(['Gold', 'Silver', 'Bronze'], dtype=object)

In [35]:
df["Medal"].value_counts()

Medal
Gold      9181
Silver    9014
Bronze    8979
Name: count, dtype: int64

In [36]:
df["NOC"].unique()

array(['FRA', 'GRE', 'USA', 'HUN', 'GER', 'AUT', 'GBR', 'AUS', 'DEN',
       'ZZX', 'SUI', 'IND', 'NED', 'CAN', 'NOR', 'BEL', 'ESP', 'BOH',
       'ITA', 'SWE', 'CUB', 'RU1', 'FIN', 'RSA', 'ANZ', 'LUX', 'EST',
       'BRA', 'JPN', 'TCH', 'NZL', 'ARG', 'HAI', 'POL', 'URU', 'YUG',
       'ROU', 'POR', 'EGY', 'PHI', 'IRL', 'CHI', 'MEX', 'LAT', 'TUR',
       'KOR', 'PAN', 'JAM', 'SRI', 'PER', 'PUR', 'IRI', 'TRI', 'URS',
       'LIB', 'BUL', 'VEN', 'EUA', 'PAK', 'ISL', 'BAH', 'BWI', 'GHA',
       'IRQ', 'SIN', 'TPE', 'ETH', 'MAR', 'TUN', 'NGR', 'KEN', 'FRG',
       'MGL', 'GDR', 'UGA', 'CMR', 'PRK', 'COL', 'NIG', 'BER', 'THA',
       'TAN', 'GUY', 'ZIM', 'ZAM', 'CHN', 'CIV', 'DOM', 'ALG', 'SYR',
       'SUR', 'CRC', 'SEN', 'AHO', 'DJI', 'ISV', 'INA', 'EUN', 'NAM',
       'IOP', 'QAT', 'ISR', 'LTU', 'CRO', 'SLO', 'MAS', 'RUS', 'UKR',
       'TGA', 'ARM', 'BLR', 'MDA', 'ECU', 'KAZ', 'AZE', 'BDI', 'SVK',
       'CZE', 'UZB', 'GEO', 'MOZ', 'HKG', 'KGZ', 'BAR', 'KSA', 'VIE',
       'MKD', 'KUW', 'ERI', 'SCG', 'UAE', 'PAR'], dtype=object)

In [37]:
len(df["NOC"].unique())

132

In [38]:
df.columns

Index(['Year', 'City', 'Sport', 'Discipline', 'Athlete Name', 'NOC', 'Gender',
       'Event', 'Event Gender', 'Medal', 'Position'],
      dtype='object')

In [39]:
df.rename(columns={'Athlete Name': 'Athlete_Name', 'Event Gender': 'Event_Gender'}, inplace=True)

In [40]:
df

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
...,...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [41]:
column_names = ['Year', 'City', 'Sport', 'Discipline', 'Athlete_Name', 'NOC', 'Gender',
                'Event', 'Event_Gender', 'Medal', 'Position']

In [42]:
df.columns = column_names

In [43]:
df = pd.read_csv("https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv", skiprows=5,
                 names=column_names)

In [44]:
df.head()

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
0,Year,City,Sport,Discipline,Athlete Name,NOC,Gender,Event,Event Gender,Medal,Position
1,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
2,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
3,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3

In [45]:
df = pd.read_csv("https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv", skiprows=5,
                 names=column_names, header=0)
df.head()

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1

In [46]:
df.drop("Position", axis=1)

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold
...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver

In [47]:
df["Year"].dtype

dtype('int64')

In [48]:
df[df["Year"] == 1896]

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
...,...,...,...,...,...,...,...,...,...,...,...
146,1896,Athens,Athletics,Athletics,"CONNOLLY, James",USA,Men,triple jump,M,Gold,1
147,1896,Athens,Athletics,Athletics,"TUFFERI, Alexandre",FRA,Men,triple jump,M,Silver,2
148,1896,Athens,Gymnastics,Artistic G.,"WEINGÄRTNER, Hermann",GER,Men,vault,M,Bronze,3
149,1896,Athens,Gymnastics,Artistic G.,"SCHUMANN, Carl",GER,Men,vault,M,Gold,1
150,1896,Athens,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,vault,M,Silver,2

In [49]:
df[df["Year"] <= 1896]

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
...,...,...,...,...,...,...,...,...,...,...,...
146,1896,Athens,Athletics,Athletics,"CONNOLLY, James",USA,Men,triple jump,M,Gold,1
147,1896,Athens,Athletics,Athletics,"TUFFERI, Alexandre",FRA,Men,triple jump,M,Silver,2
148,1896,Athens,Gymnastics,Artistic G.,"WEINGÄRTNER, Hermann",GER,Men,vault,M,Bronze,3
149,1896,Athens,Gymnastics,Artistic G.,"SCHUMANN, Carl",GER,Men,vault,M,Gold,1
150,1896,Athens,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,vault,M,Silver,2

In [50]:
df[df["Year"] <= 1896]

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
...,...,...,...,...,...,...,...,...,...,...,...
146,1896,Athens,Athletics,Athletics,"CONNOLLY, James",USA,Men,triple jump,M,Gold,1
147,1896,Athens,Athletics,Athletics,"TUFFERI, Alexandre",FRA,Men,triple jump,M,Silver,2
148,1896,Athens,Gymnastics,Artistic G.,"WEINGÄRTNER, Hermann",GER,Men,vault,M,Bronze,3
149,1896,Athens,Gymnastics,Artistic G.,"SCHUMANN, Carl",GER,Men,vault,M,Gold,1
150,1896,Athens,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,vault,M,Silver,2

In [51]:
df["City"].dtype

dtype('O')

In [52]:
df[df["City"] == "Athens"]

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
...,...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [53]:
df[(df["Year"] == 1896) | (df["Year"] == 2004)]

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
...,...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [54]:
df[(df["City"] == "Athens") & (df["Year"] == 2004)]

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
25176,2004,Athens,Judo,Judo,"PERTELSON, Indrek",EST,Men,+ 100kg (heavyweight),M,Bronze,3
25177,2004,Athens,Judo,Judo,"VAN DER GEEST, Dennis",NED,Men,+ 100kg (heavyweight),M,Bronze,3
25178,2004,Athens,Judo,Judo,"SUZUKI, Keiji",JPN,Men,+ 100kg (heavyweight),M,Gold,1
25179,2004,Athens,Judo,Judo,"TMENOV, Tamerlan",RUS,Men,+ 100kg (heavyweight),M,Silver,2
25180,2004,Athens,Weightlifting,Weightlifting,"CHOLAKOV, Velichko",BUL,Men,+ 105kg,M,Bronze,3
...,...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [55]:
df[(df["City"] == "Athens") & ~(df["Year"] == 1896)]

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
25176,2004,Athens,Judo,Judo,"PERTELSON, Indrek",EST,Men,+ 100kg (heavyweight),M,Bronze,3
25177,2004,Athens,Judo,Judo,"VAN DER GEEST, Dennis",NED,Men,+ 100kg (heavyweight),M,Bronze,3
25178,2004,Athens,Judo,Judo,"SUZUKI, Keiji",JPN,Men,+ 100kg (heavyweight),M,Gold,1
25179,2004,Athens,Judo,Judo,"TMENOV, Tamerlan",RUS,Men,+ 100kg (heavyweight),M,Silver,2
25180,2004,Athens,Weightlifting,Weightlifting,"CHOLAKOV, Velichko",BUL,Men,+ 105kg,M,Bronze,3
...,...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2

In [56]:
first_men_100m = df.loc[(df["Year"] == 1896) & (df["Gender"] == "Men") & (df["Event"] == "100m")]

In [57]:
first_men_100m

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
2,1896,Athens,Athletics,Athletics,"LANE, Francis",USA,Men,100m,M,Bronze,3
3,1896,Athens,Athletics,Athletics,"SZOKOLYI, Alajos",HUN,Men,100m,M,Bronze,3
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1
5,1896,Athens,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver,2

In [58]:
len(first_men_100m)

4

In [59]:
first_men_100m[["Year", "Medal"]]

   Year   Medal
2  1896  Bronze
3  1896  Bronze
4  1896    Gold
5  1896  Silver

In [60]:
first_men_100m_with_selected_columns = df.loc[
    (df["Year"] == 1896) & (df["Gender"] == "Men") & (df["Event"] == "100m"), ["Year", "Medal"]]

In [61]:
first_men_100m_with_selected_columns

   Year   Medal
2  1896  Bronze
3  1896  Bronze
4  1896    Gold
5  1896  Silver

In [62]:
df["Athlete_Name"].str.lower()

0             flameng, léon
1        kolettis, georgios
2             lane, francis
3          szokolyi, alajos
4             burke, thomas
                ...
27169    logounova, tatiana
27170         sivkova, anna
27171        bokel, claudia
27172       duplitzer, imke
27173     heidemann, britta
Name: Athlete_Name, Length: 27174, dtype: object

In [63]:
df["Event"].unique()

array(['100km', '100m', '100m freestyle', '100m freestyle for sailors',
       '10km', '110m hurdles', '12-hour race', '1200m freestyle', '1500m',
       '1km time trial', '25m army pistol',
       '25m rapid fire pistol (60 shots)', '400m', '400m freestyle',
       '50m pistol (60 shots)', '800m', 'Sprint indivual',
       'army rifle, 200m', 'army rifle, 300m', 'discus throw', 'doubles',
       'foil individual', 'foil, masters', 'heavyweight - one hand lift',
       'heavyweight - two hand lift', 'high jump', 'horizontal bar',
       'individual road race', 'long jump', 'marathon', 'open event',
       'parallel bars', 'pole vault', 'pommel horse', 'rings',
       'rope climbing', 'sabre individual', 'shot put', 'singles',
       'team, horizontal bar', 'team, parallel bars', 'triple jump',
       'vault', '0.5-1t', '10-20t', '1500m freestyle', '200m',
       '200m backstroke', '200m freestyle', '200m hurdles',
       '200m obstacle event', '200m team swimming', '25 kilometres',
       '3-10t', '3000m steeplechase', '4000m freestyle',
       '4000m steeplechase', '400m hurdles', '5000m team',
       '50m army pistol, team', '60m', 'army rifle, 300m, 3 positions',
       'army rifle, 300m, kneeling', 'army rifle, 300m, prone',
       'army rifle, 300m, standing', 'au chapelet, 33m',
       'au chapelet, 50m', 'au cordon doré, 33m', 'au cordon doré, 50m',
       'cesta punta', 'cricket', 'double', 'eight with coxswain (8+)',
       'football', 'four-oared shell with coxswain (4-)',
       'free rifle, team', 'hammer throw', 'high jump, standing',
       'individual', 'individual 1 ball', 'individual 2 balls',
       'individual all-round', 'long jump individual',
       'long jump, standing', 'mixed doubles', 'open class',
       'pair-oared shell with coxswain (2+)', 'polo', 'rugby',
       'sabre, masters', 'single sculls (1x)', 'sur la perche à la herse',
       'sur la perche à la pyramide', 'trap (125 targets)',
       'triple jump, standing', 'tug of war', 'underwater swimming',
       'water polo', 'épée individual', 'épée, amateurs and masters',
       'épée, masters', '+ 71.67kg (heavyweight)',
       '- 47.63kg (flyweight)', '- 47.6kg (light-flyweight)',
       '1 mile (1609.3m)', '1/2 mile (804.7m)', '1/3 mile (536.5m)',
       '1/4 mile (402.3m)', '100m backstroke', '10m platform',
       '2 miles (3.218km)', '25 miles (40.232km)', '400m breaststroke',
       '47.6 - 52.16kg (flyweight)', '47.63 - 52.16kg (bantamweight)',
       '4miles team', '4x50y freestyle relay', '5 miles (8.046km)',
       '50y freestyle (45.72m)', '52.16 - 56.7kg (bantamweight)',
       '52.16 - 56.7kg (featherweight)', '56.7 - 61.23kg (featherweight)',
       '56.7 - 61.24kg (lightweight)', '56lb weight throw (25.4kg)',
       '61.23 - 65.77kg (lightweight)', '61.24 - 65.77kg (welterweight)',
       '65.77 - 71.67kg (middleweight)', '65.77 - 71.67kg (welterweight)',
       '880y freestyle (804.66m)', 'all-around Dumbbell contest',
       'club swinging', 'combined 3 events', 'combined 4 events',
       'coxless pair (2-)', 'decathlon',
       'double american round (60y - 50y - 40y)',
       'double columbia round (50y - 40y - 30y)',
       'double national round (60y - 50y)', 'double sculls (2x)',
       'double york round (100y - 80y - 60y)', 'foil team',
       'four without coxswain (4-)', 'lacrosse', 'plunge for distance',
       'stick, single', 'team', 'team competition', 'team round 60y',
       'teams FITA round', 'triathlon (long jump / shot put / 100 yards)',
       '+ 73kg (heavyweight)', '+ 93kg (super heavyweight)',
       '- 52.62kg (bantamweight)', '- 54kg (bantamweight)',
       '- 66.6kg (lightweight)', '1000y free rifle, prone',
       '100m running deer, double shots',
       '100m running deer, single shots',
       '100m running deer, single shots, team', '10miles walk (16093m)',
       '12m', '1980 yards Pursuit, Team', '2000m tandem',
       '200m breaststroke', '20km',
       '25y small bore rifle, disappearing target',
       '25y small bore rifle, moving target',
       '300m free rifle 3 positions (3x40 shots)', '3200m steeplechase',
       '3500m walk', '3m springboard', '3miles team (4828m)',
       '4x200m freestyle relay', '4x400m relay', '5 miles (8047m)',
       '50+100y small bore rifle, team', '5000m',
       '50m rifle prone (60 shots)', '50y army pistol, team',
       '52.62 - 57.15kg (featherweight)', '54 - 60.3kg (featherweight)',
       '57.15 - 63.5kg (lightweight)', '60.3 - 66.6kg (lightweight)',
       '63.5 - 71.67kg (middleweight)', '66.6 - 73kg (middleweight)',
       '6m', '73 - 93kg (light-heavyweight)', '7m', '8m', '8m class C',
       'One lap (660y) sprint', 'class B up to 60 feet',
       'clay pigeons, team', 'continental style 50m',
       'discus throw ancient style', 'doubles indoor', 'hockey',
       'javelin throw', 'javelin throw freestyle',
       'national round (60y - 50y)', 'open class A', 'pairs',
       'rifle, team', 'sabre team', 'singles indoor', 'special figures',
       'york round (100y - 80y - 60y)', 'épée team',
       '+ 82.5kg (super heavyweight)', '- 60kg (featherweight)', '10000m',
       '10000m walk', '10m', '25m small bore rifle, team',
       '25m small rifle', '3000m team', '30m army pistol, team',
       '4x100m freestyle relay', '4x100m relay',
       '50m small bore rifle, team', '60 - 67.5kg (lightweight)',
       '600m free rifle', '67.5 - 75kg (middleweight)',
       '75 - 82.5kg (light-heavyweight)', 'Individual competition',
       'coxed fours Jugriggers', 'cross country individual',
       'cross country team', 'discus throw, both hands',
       'individual time trial', 'javelin throw, both hands',
       'mixed doubles indoor', 'pentathlon', 'plain high diving',
       'shot put, both hands', 'team time trial', 'team, Swedish system',
       'team, free system', '+ 79.38kg (heavyweight)',
       '+ 80kg (heavyweight)',
       '+ 82.5kg, one-two hand 3 events (heavyweight)',
       '+ 82kg (super heavyweight)', '- 50.8kg (flyweight)',
       '- 60kg, one-two hand 3 events (featherweight)',
       '100m running deer, double shots, team', '10m (rating 1907)',
       '10m (rating 1919)', '12 foot dinghy', '12m (rating 1907)',
       '12m (rating 1919)', '18 foot dinghy',
       '300+600m free rifle, team, prone', '3000m walk',
       '300m free rifle, prone, team', '300m free rifle, standing, team',
       '30m sq', '40m sq', '50.8 - 53.52kg (bantamweight)', '50km',
       '50m small bore rifle, standing, individual',
       '53.52 - 57.15kg (featherweight)', '57.15 - 61.24kg (lightweight)',
       '6.5m (rating 1919)',
       '60 - 67.5kg, one-two hand 3 events (lightweight)',
       '600m free rifle, prone', '600m free rifle, team',
       '61.24 - 66.68kg (welterweight)', '66.68 - 72.57kg (middleweight)',
       '67.5 - 75kg, one-two hand 3 events (middleweight)',
       '6m (rating 1907)', '6m (rating 1919)',
       '72.57 - 79.38kg (light-heavyweight)',
       '75 - 80kg (light-heavyweight)',
       '75 - 82.5kg, one-two hand 3 e. (light-heavyweight)',
       '75 - 82kg (light-heavyweight)', '8m (rating 1907)',
       '8m (rating 1919)', 'Team Pursuit (4000m)',
       'figure riding individual', 'figure riding team',
       'fixed bird target large birds',
       'fixed bird target large birds teams',
       'fixed bird target small bird, teams',
       'fixed bird target small birds', 'ice hockey',
       'moving bird target 28m teams', 'moving bird target 33m teams',
       'moving bird target 50m teams', 'moving bird target, 28m',
       'moving bird target, 33m', 'moving bird target, 50m',
       '+ 82.5kg, one-two hand 5 events (heavyweight)',
       '+ 87kg (heavyweight)', '- 56kg (bantamweight)',
       '- 58kg (bantamweight)',
       '- 60kg, one-two hand 5 events (featherweight)',
       '400, 600, 800m free rifle, team', '56 - 61kg (featherweight)',
       '58 - 62kg (featherweight)',
       '60 - 67.5kg, one-two hand 5 events (lightweight)',
       '600m free rifle, individual', '61 - 66kg (lightweight)',
       '62 - 67.5kg (lightweight)', '66 - 72kg (welterweight)',
       '67.5 - 75kg, one-two hand 5 events (middleweight)',
       '72 - 79kg (middleweight)',
       '75 - 82.5kg, one-two hand 5 e. (light-heavyweight)',
       '79 - 87kg (light-heavyweight)', 'Sidehorse vault',
       'olympic class monotype', '+ 82.5kg, total (heavyweight)',
       '- 60kg, total (featherweight)', '12 foot dinghy individual',
       '1km Pursuit', '58 - 60kg (featherweight)',
       '60 - 67.5kg, total (lightweight)',
       '67.5 - 75kg, total (middleweight)',
       '75 - 82.5kg, total (light-heavyweight)',
       '+ 87kg (super heavyweight)', '50.8 - 54kg (bantamweight)',
       '50km walk', '54 - 57.15kg (featherweight)', '80m hurdles',
       'floor exercises', 'indian clubs', 'tumbling',
       'two-person keelboat open (Star)', 'C-1 1000m (canoe single)',
       'C-2 10000m', 'C-2 1000m (canoe double)', 'K-1 10000m',
       'K-1 1000m (kayak single)', 'K-2 10000m',
       'K-2 1000m (kayak double)', 'basketball', 'folding K-1 10000m',
       'folding K-2 10000m', 'handball', '- 51kg (flyweight)',
       '- 52kg (flyweight)', '- 56kg, total (bantamweight)',
       '51 - 54kg (bantamweight)', '52 - 57kg (bantamweight)',
       '54 - 58kg (featherweight)', '56 - 60kg, total (featherweight)',
       '57 - 61kg (featherweight)', '57 - 63kg (featherweight)',
       '58 - 62kg (lightweight)', '61 - 67kg (lightweight)',
       '62 - 67kg (welterweight)', '63 - 67kg (lightweight)',
       '67 - 73kg (middleweight)', '67 - 73kg (welterweight)',
       '73 - 79kg (middleweight)', '73 - 80kg (light-heavyweight)',
       'C-1 10000m', 'K-1 500m (kayak single)', 'dragon', 'firefly class',
       'swallow (golondrina)', '+ 81kg (heavyweight)',
       '+ 90kg, total (heavyweight)',
       '100m running deer, single/double shots', '5.5m',
       '50m rifle 3 positions (3x40 shots)', '54 - 57kg (featherweight)',
       '57 - 60kg (lightweight)', '60 - 63.5kg (light-welterweight)',
       '63.5 - 67kg (welterweight)', '67 - 71kg (light-middleweight)',
       '71-75kg', '75 - 81kg (light-heavyweight)',
       '82.5 - 90kg, total (middle-heavyweight)', 'Team competition',
       'balance beam', 'single-handed dinghy (Finn)',
       'team, portable apparatus', 'uneven bars', '100m butterfly',
       '200m butterfly', '20km walk', 'sharpie 12m2',
       '4x100m medley relay', 'K-1 4x500m', 'K-2 500m (kayak double)',
       'flying dutchman', '+ 97kg (heavyweight)',
       '+ 97kg (super heavyweight)', '- 68kg (lightweight)',
       '400m individual medley', '63 - 70kg (lightweight)',
       '68 - 80kg (middleweight)', '70 - 78kg (welterweight)',
       '78 - 87kg (middleweight)', '87 - 97kg (light-heavyweight)',
       'Individual Pursuit', 'K-4 1000m (kayak four)', 'open category',
       'volleyball', '- 48kg (light-flyweight)', '100m breaststroke',
       '200m individual medley', '48 - 51kg (flyweight)',
       '800m freestyle', 'skeet (125 targets)',
       '+ 100kg (super heavyweight)',
       '+ 110kg, total (super heavyweight)', '+ 93kg (heavyweight)',
       '- 52kg, total (flyweight)', '- 63kg (lightweight)',
       '100m hurdles', '48 - 52kg (flyweight)',
       '50m running target (30+30 shots)',
       '52 - 56kg, total (bantamweight)', '57 - 62kg (featherweight)',
       '62 - 68kg (lightweight)', '63 - 70kg (half-middleweight)',
       '68 - 74kg (welterweight)', '70 - 80kg (middleweight)',
       '74 - 82kg (middleweight)', '80 - 93kg (half-heavyweight)',
       '82 - 90kg (light-heavyweight)', '90 - 100kg (heavyweight)',
       '91 - 110kg, total (heavyweight)', 'C-1 (canoe single)',
       'C-2 (canoe double)', 'K-1 (kayak single)',
       'fleet/match race keelboat open (Soling)', 'individual FITA round',
       'tempest', '470 - Two Person Dinghy', 'C-1 500m (canoe single)',
       'C-2 500m (canoe double)', 'Tornado - Multihull',
       'pair without coxswain (2-)',
       'quadruple sculls with coxswain (4x)',
       'quadruple sculls without coxswain (4x)', '+ 95kg (heavyweight)',
       '- 60 kg', '100 - 110kg, total (heavyweight)',
       '60 - 65kg (half-lightweight)', '65 - 71kg (lightweight)',
       '71 - 78kg (half-middleweight)', '78 - 86kg (middleweight)',
       '86 - 95kg (half-heavyweight)',
       '90 - 100kg, total (first-heavyweight)',
       '+ 91kg (super heavyweight)', '10m air rifle (40 shots)',
       '10m air rifle (60 shots)', '25m pistol (30+30 shots)', '3000m',
       '50m rifle 3 positions (3x20 shots)', '81 - 91kg (heavyweight)',
       'K-4 500m (kayak four)', 'Points Race', 'board (windglider)',
       'duet', 'heptathlon', 'solo', '100 - 130kg (super heavyweight)',
       '10m air pistol (40 shots)', '10m air pistol (60 shots)',
       '50m freestyle', 'board (division II)', 'sprint',
       '+ 72kg (heavyweight)', '- 48kg (extra-lightweight)',
       '48 - 52kg (half-lightweight)', '52 - 56kg (lightweight)',
       '56 - 61kg (half-middleweight)', '61 - 66kg (middleweight)',
       '66 - 72kg (half-heavyweight)', 'baseball', 'board (lechner)',
       'coxless four (4-)', 'individual (FITA Olympic round - 70m)',
       'individual pursuit', 'single-handed dinghy (Europe)',
       'team (FITA Olympic round - 70m)', '+ 100kg (heavyweight)',
       '+ 108kg, total (super heavyweight)', '- 54kg, total (flyweight)',
       '54 - 59kg, total (bantamweight)',
       '59 - 64kg, total (featherweight)', '60 - 66kg (half-lightweight)',
       '64 - 70kg, total (lightweight)', '66 - 73kg (lightweight)',
       '70 - 76kg, total (middleweight)', '73 - 81kg (half-middleweight)',
       '76 - 83kg, total (light-heavyweight)', '81 - 90kg (middleweight)',
       '83 - 91kg, total (middle-heavyweight)',
       '90 - 100kg (half-heavyweight)',
       '91 - 99kg, total (first-heavyweight)',
       '99 - 108kg, total (heavyweight)', 'beach volleyball',
       'board (Mistral)', 'cross-country', 'double trap (120 targets)',
       'double trap (150 targets)', 'group competition',
       'lightweight coxless four (4-)', 'lightweight double sculls (2x)',
       'points race', 'single-handed dinghy open (Laser)', 'softball',
       '+ 105kg', '+ 67 kg', '+ 75kg', '+ 78kg (heavyweight)', '+ 80 kg',
       '- 49 kg', '- 58 kg', '105kg', '10m running target (30+30 shots)',
       '20km race walk', '48 - 54kg', '48kg', '49 - 57 kg',
       '49er - Skiff', '500m time trial', '52 - 57kg (lightweight)',
       '53kg', '54 - 58kg', '56kg', '57 - 63kg (half-middleweight)',
       '57 - 67 kg', '58 - 63kg', '58 - 68 kg', '58kg', '62kg',
       '63 - 69kg', '63 - 70kg (middleweight)', '63kg', '68 - 80 kg',
       '69 - 76kg', '69kg', '70 - 78kg (half-heavyweight)', '75kg',
       '76 - 85kg', '77kg', '85 - 97kg', '85kg', '94kg', '97 - 130kg',
       'Individual', 'Keirin', 'Madison', 'Olympic Sprint',
       'skeet (75 targets)', 'synchronized diving 10m platform',
       'synchronized diving 3m springboard', 'trap (75 targets)',
       '- 48 kg', '- 48kg', '- 55kg', '48 - 55kg',
       '48kg (light flywieght)', '55 - 60kg', '55 - 63kg', '60 - 64 kg',
       '60 - 66kg', '63 - 72kg', '64 - 69 kg', '66 - 74kg', '69 - 75 kg',
       '74 - 84kg', '84 - 96kg', '96 - 120kg', 'Star - Keelboat',
       'Team Sprint', 'Yngling - Keelboat'], dtype=object)

In [64]:
len(df["Event"].unique())

572

In [65]:
len(df["Event"].str.capitalize().unique())

568

In [66]:
df[df["Athlete_Name"].str.contains("LATYNINA")]

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position
9372,1956,Melbourne / Stockholm,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,floor exercises,W,Gold,1
9539,1956,Melbourne / Stockholm,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,individual all-round,W,Gold,1
9679,1956,Melbourne / Stockholm,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,team competition,W,Gold,1
9702,1956,Melbourne / Stockholm,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,"team, portable apparatus",W,Bronze,3
9735,1956,Melbourne / Stockholm,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,uneven bars,W,Silver,2
9741,1956,Melbourne / Stockholm,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,vault,W,Gold,1
10179,1960,Rome,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,balance beam,W,Silver,2
10277,1960,Rome,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,floor exercises,W,Gold,1
10458,1960,Rome,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,individual all-round,W,Gold,1
10576,1960,Rome,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,team competition,W,Gold,1
10612,1960,Rome,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,uneven bars,W,Silver,2
10616,1960,Rome,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,vault,W,Bronze,3
11095,1964,Tokyo,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,balance beam,W,Bronze,3
11195,1964,Tokyo,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,floor exercises,W,Gold,1
11387,1964,Tokyo,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,individual all-round,W,Silver,2
11517,1964,Tokyo,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,team competition,W,Gold,1
11551,1964,Tokyo,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,uneven bars,W,Bronze,3
11558,1964,Tokyo,Gymnastics,Artistic G.,"LATYNINA, Larisa",URS,Women,vault,W,Silver,2

In [67]:
df["Date"] = pd.to_datetime(df["Year"].astype(str), format="%Y")

In [68]:
from datetime import date
from datetime import datetime

x = 2005

datetime.strptime(str(x), "%Y").date()

datetime.date(2005, 1, 1)

In [69]:
df["Date"]

0       1896-01-01
1       1896-01-01
2       1896-01-01
3       1896-01-01
4       1896-01-01
           ...
27169   2004-01-01
27170   2004-01-01
27171   2004-01-01
27172   2004-01-01
27173   2004-01-01
Name: Date, Length: 27174, dtype: datetime64[ns]

In [70]:
df["Date"].dt.month

0        1
1        1
2        1
3        1
4        1
        ..
27169    1
27170    1
27171    1
27172    1
27173    1
Name: Date, Length: 27174, dtype: int32

In [71]:
df["Date"].dt.year

0        1896
1        1896
2        1896
3        1896
4        1896
         ...
27169    2004
27170    2004
27171    2004
27172    2004
27173    2004
Name: Date, Length: 27174, dtype: int32

In [72]:
df["Date"].dt.strftime("%m | %Y")

0        01 | 1896
1        01 | 1896
2        01 | 1896
3        01 | 1896
4        01 | 1896
           ...
27169    01 | 2004
27170    01 | 2004
27171    01 | 2004
27172    01 | 2004
27173    01 | 2004
Name: Date, Length: 27174, dtype: object

In [73]:
dir(float)

['__abs__',
 '__add__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getformat__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__le__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 'as_integer_ratio',
 'conjugate',
 'fromhex',
 'hex',
 'imag',
 'is_integer',
 'real']

In [74]:
4.2.is_integer()

False

In [75]:
float.is_integer(4.2)

False

In [76]:
(4.2).is_integer()

False

In [77]:
float.conjugate?

In [78]:
df["Athlete_Name"].sort_values()

611                 AABYE, Edgar
3060       AALTONEN, Arvo Ossian
2963       AALTONEN, Arvo Ossian
7792    AALTONEN, Paavo Johannes
7906    AALTONEN, Paavo Johannes
                  ...
275                   ÖSTMO, Ole
443                   ÖSTMO, Ole
280                   ÖSTMO, Ole
268                   ÖSTMO, Ole
8125           ÖSTRAND, Per-Olof
Name: Athlete_Name, Length: 27174, dtype: object

In [79]:
type(df["Athlete_Name"].sort_values())

pandas.core.series.Series

In [80]:
df.sort_values("Athlete_Name")

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position,Date
611,1900,Paris,Tug of War,Tug of War,"AABYE, Edgar",ZZX,Men,tug of war,M,Gold,1,1900-01-01
3060,1920,Antwerp,Aquatics,Swimming,"AALTONEN, Arvo Ossian",FIN,Men,400m breaststroke,M,Bronze,3,1920-01-01
2963,1920,Antwerp,Aquatics,Swimming,"AALTONEN, Arvo Ossian",FIN,Men,200m breaststroke,M,Bronze,3,1920-01-01
7792,1948,London,Gymnastics,Artistic G.,"AALTONEN, Paavo Johannes",FIN,Men,individual all-round,M,Bronze,3,1948-01-01
7906,1948,London,Gymnastics,Artistic G.,"AALTONEN, Paavo Johannes",FIN,Men,team competition,M,Gold,1,1948-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...
275,1900,Paris,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"army rifle, 300m, prone",M,Bronze,3,1900-01-01
443,1900,Paris,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"free rifle, team",M,Silver,2,1900-01-01
280,1900,Paris,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"army rifle, 300m, standing",M,Silver,2,1900-01-01
268,1900,Paris,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"army rifle, 300m, 3 positions",M,Bronze,3,1900-01-01
8125,1952,Helsinki,Aquatics,Swimming,"ÖSTRAND, Per-Olof",SWE,Men,400m freestyle,M,Bronze,3,1952-01-01

In [81]:
type(df.sort_values("Athlete_Name"))

pandas.core.frame.DataFrame

In [82]:
df.sort_values(by=["Year", "Athlete_Name"], ascending=[False, True])

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position,Date
25212,2004,Athens,Wrestling,Wrestling Free.,"ABAS, Stephen",USA,Men,- 55kg,M,Silver,2,2004-01-01
26832,2004,Athens,Cycling,Cycling Track,"ABASSOVA, Tamilla",RUS,Women,sprint,W,Silver,2,2004-01-01
25418,2004,Athens,Taekwondo,Taekwondo,"ABDALLAH, Nia",USA,Women,49 - 57 kg,W,Silver,2,2004-01-01
25726,2004,Athens,Wrestling,Wrestling Gre-R,"ABRAHAMIAN, Ara",SWE,Men,74 - 84kg,M,Silver,2,2004-01-01
26997,2004,Athens,Volleyball,Volleyball,"ABRAMOV, Pavel",RUS,Men,volleyball,M,Bronze,3,2004-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...
104,1896,Athens,Gymnastics,Artistic G.,"XENAKIS, Thomasios",GRE,Men,rope climbing,M,Silver,2,1896-01-01
144,1896,Athens,Gymnastics,Artistic G.,"XENAKIS, Thomasios",GRE,Men,"team, parallel bars",M,Silver,2,1896-01-01
92,1896,Athens,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,parallel bars,M,Silver,2,1896-01-01
97,1896,Athens,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,pommel horse,M,Gold,1,1896-01-01
150,1896,Athens,Gymnastics,Artistic G.,"ZUTTER, Louis",SUI,Men,vault,M,Silver,2,1896-01-01

In [83]:
"" > ""

False

In [84]:
None > None

TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

In [86]:
import numpy as np

np.nan > np.nan

False

In [87]:
df["Medal"].unique()

array(['Gold', 'Silver', 'Bronze'], dtype=object)

In [88]:
df["Medal"] = df["Medal"].astype("category")

In [89]:
df["Medal"].dtype

CategoricalDtype(categories=['Bronze', 'Gold', 'Silver'], ordered=False, categories_dtype=object)

In [90]:
df["Medal"] = pd.Categorical(
    df["Medal"],
    categories=["Bronze", "Silver", "Gold"],
    ordered=True
)

In [91]:
df.sort_values("Medal", ascending=False).head()

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position,Date
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1,1896-01-01
6661,1936,Berlin,Basketball,Basketball,"BALTER, Samuel J. Jr.",USA,Men,basketball,M,Gold,1,1936-01-01
6663,1936,Berlin,Basketball,Basketball,"FORTENBERRY, Joseph Cephis",USA,Men,basketball,M,Gold,1,1936-01-01
6664,1936,Berlin,Basketball,Basketball,"GIBBONS, John Haskell",USA,Men,basketball,M,Gold,1,1936-01-01
6665,1936,Berlin,Basketball,Basketball,"JOHNSON, Francis Lee",USA,Men,basketball,M,Gold,1,1936-01-01

In [92]:
df[df["Medal"] > "Bronze"]

,Year,City,Sport,Discipline,Athlete_Name,NOC,Gender,Event,Event_Gender,Medal,Position,Date
0,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100km,M,Gold,1,1896-01-01
1,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100km,M,Silver,2,1896-01-01
4,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100m,M,Gold,1,1896-01-01
5,1896,Athens,Athletics,Athletics,"HOFMANN, Fritz",GER,Men,100m,M,Silver,2,1896-01-01
6,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100m freestyle,M,Gold,1,1896-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...
27169,2004,Athens,Fencing,Fencing,"LOGOUNOVA, Tatiana",RUS,Women,épée team,W,Gold,1,2004-01-01
27170,2004,Athens,Fencing,Fencing,"SIVKOVA, Anna",RUS,Women,épée team,W,Gold,1,2004-01-01
27171,2004,Athens,Fencing,Fencing,"BOKEL, Claudia",GER,Women,épée team,W,Silver,2,2004-01-01
27172,2004,Athens,Fencing,Fencing,"DUPLITZER, Imke",GER,Women,épée team,W,Silver,2,2004-01-01
27173,2004,Athens,Fencing,Fencing,"HEIDEMANN, Britta",GER,Women,épée team,W,Silver,2,2004-01-01

In [93]:
df["Medal"].cat.codes

0        2
1        1
2        0
3        0
4        2
        ..
27169    2
27170    2
27171    1
27172    1
27173    1
Length: 27174, dtype: int8

In [94]:
df["Event"] = df["Event"].astype(str)
df["Gender"] = df["Gender"].astype(str)

df["Event Gender"] = df["Event"] + "_" + df["Gender"]
df["Event Gender"] = df["Event Gender"].astype("category")

In [95]:
df["Event Gender"].unique()

['100km_Men', '100m_Men', '100m freestyle_Men', '100m freestyle for sailors_Men', '10km_Men', ..., '96 - 120kg_Men', 'Star - Keelboat_Men', 'Team Sprint_Men', 'Yngling - Keelboat_Women', 'sabre individual_Women']
Length: 664
Categories (664, object): ['+ 100kg (heavyweight)_Men', '+ 100kg (super heavyweight)_Men', '+ 105kg_Men', '+ 108kg, total (super heavyweight)_Men', ..., 'épée team_Men', 'épée team_Women', 'épée, amateurs and masters_Men', 'épée, masters_Men']

In [96]:
ordered_medals = pd.CategoricalDtype(categories=["Bronze", "Silver", "Gold"], ordered=True)
ordered_medals

CategoricalDtype(categories=['Bronze', 'Silver', 'Gold'], ordered=True, categories_dtype=object)

In [118]:
dtype_mapper = {"Year": "int64",
                "City": "string",
                "Sport": "string",
                "Discipline": "string",
                "Athlete Name": "string",
                "NOC": "string",
                "Gender": "category",
                "Event": "string",
                "Event_Gender": "category",
                "Medal": ordered_medals}

dtype_mapper

{'Year': 'int64',
 'City': 'string',
 'Sport': 'string',
 'Discipline': 'string',
 'Athlete Name': 'string',
 'NOC': 'string',
 'Gender': 'category',
 'Event': 'string',
 'Event_Gender': 'category',
 'Medal': CategoricalDtype(categories=['Bronze', 'Silver', 'Gold'], ordered=True, categories_dtype=object)}

In [119]:
df = pd.read_csv("https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv", skiprows=5, dtype=dtype_mapper)

In [120]:
df.dtypes

Year                     int64
City            string[python]
Sport           string[python]
Discipline      string[python]
Athlete Name    string[python]
NOC             string[python]
Gender                category
Event           string[python]
Event Gender            object
Medal                 category
Position                 int64
dtype: object

In [121]:
from pandas._typing import FilePath, ReadCsvBuffer

type CSVBuffer = FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]

In [122]:
def check_columns(file_path_of_buffer: CSVBuffer, cols_mapper: dict[str, str | pd.Categorical], skiprows: int = 0) -> set[str]:
    cols = pd.read_csv(file_path_of_buffer, skiprows=skiprows, nrows=0).columns.tolist()
    cols_set = set(cols)
    cols_mapper_set = set(cols_mapper)
    return cols_set - cols_mapper_set

In [123]:
file_path = "https://github.com/jonfernandes/pandas_essential/raw/main/olympics_1896_2004.csv"

In [124]:
check_columns(file_path, dtype_mapper, skiprows=5)

{'Event Gender', 'Position'}